# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '1701Portal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 1701Portal
  pod 'AFNetworking', '~> 4.0.1'
  pod 'MBProgressHUD'
  pod ‘MJExtension’, ‘3.0.13’
  pod ‘IQKeyboardManager’,’4.0.10’
  pod ‘Masonry’,’1.0.2’
  pod 'SDWebImage','5.0.2'
  pod 'MJRefresh',   '~> 3.5.0'
  pod 'JXCategoryView', '~> 1.5.8'
  pod 'JXPagingView/Pager', '~> 2.1.1'
  pod 'SDCycleScrollView'
  pod 'WechatOpenSDK'
  

  target '1701PortalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '1701PortalUITests' do
    # Pods for testing
  end

end
